dc_token = "MTAyMDA4MjQ4NzkyMzMxNDcyOQ.GeNlu1.3NKeaDBttpZRCqssPRASIRhT7nLXAE60FT4b2g"
deepl_api_key = "f11eec37-119e-66c5-3b99-9d3b6e91a9fd:fx"

debug = true
welcome_message = true

welcome_message_text = """
Willkommen auf dem IDIC Server.
Bitte verwenden auf dem Server denselben Namen wie im Spiel.
Weitere Rechte und somit Channelzugriffe werden in Kürze zugewiesen.
Auf unserem Discordserver können Nachrichten automatisch übersetzt werden, indem als Reaktion die entsprechende
Länderflagge ausgewählt wird.
Zur Verfügung stehen folgende Sprachen:
Welcome to the IDIC server.
Please use the same name on the server as in the game.
Further rights and thus channel accesses will be assigned shortly.
On our discord server, messages can be translated automatically by selecting the appropriate country flag as a response.
The following languages are available:
🇧🇬 🇨🇿 🇩🇰 🇩🇪 🇬🇧 🇺🇲 🇪🇸 🇪🇪 🇫🇮 🇫🇷 🇭🇺 🇮🇹 🇯🇵 🇱🇹 🇱🇻 🇳🇱 🇵🇱 🇵🇹 🇷🇴 🇷🇺 🇸🇰 🇸🇮 🇸🇪 🇨🇳"""